apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-deployment-example
spec:
  name: sklearn-custom-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: quay.io/kachau/seldon-custom-model:latest
          name: sklearn-custom-classifier
          imagePullPolicy: Always
          env:
          - name: GUNICORN_WORKERS
            value: '1'
          - name: GUNICORN_THREADS
            value: '2'
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: S3_ENDPOINT
                name: github-pr-ttm-secret
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: S3_ACCESS_KEY
                name: github-pr-ttm-secret
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: S3_SECRET_KEY
                name: github-pr-ttm-secret
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: S3_BUCKET
                name: github-pr-ttm-secret
          - name: S3_MODEL_KEY
            valueFrom:
              secretKeyRef:
                key: S3_MODEL_KEY
                name: github-pr-ttm-secret
    graph:
      children: []
      endpoint:
        type: REST
      name: sklearn-custom-classifier
      type: MODEL
    name: sklearn-custom-predictor
    replicas: 1